"""Initial migration.

Revision ID: 543fa91c5b70
Revises: 
Create Date: 2024-11-01 16:01:50.594842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543fa91c5b70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
